---
- name: Install network-manager
  ansible.builtin.package:
    name: network-manager
    state: present 
  become: yes

- name: Set IP Address
  community.general.nmcli:
    conn_name: pgbgp-sim
    ifname: ens160
    type: ethernet
    ip4: "10.0.{{ node_id }}.1/24"
    #    gw4: 10.0.12.1
    #    ipv4: "{{ ip }}"
    #gw4: "{{ gw }}"
    state: present
  become: yes
  when: node_id is defined

- name: Set IP Address
  community.general.nmcli:
    conn_name: pgbgp-sim
    ifname: ens160
    type: ethernet
    ip4: "{{ ip }}"
    gw4: "{{ gw }}"
    state: present
  become: yes
  when: ip is defined
