---

- include_tasks:
    file: router.yml
  when: node_id is defined
  tags:
    - router
    - frrouting

- include_tasks:
    file: terminal.yml
  when: ip is defined
  tags: terminal


- name: Enable packet forwarding
  command: "sudo sysctl -w net.ipv4.ip_forward=1"
