---

- include_tasks:
    file: router.yml
  when: node_id is defined
  tags:
    - router
    - brrouting

- include_tasks:
    file: terminal.yml
  when: ip is defined
  tags: terminal

    #- name: Restart network
  #command: systemctl restart NetworkManager.service
  #  become: yes
