---
- name: Set IP Address for router
  command: "ip a add 10.0.{{ node_id }}.1/24 dev ens160"
  when: node_id is defined
  become: yes
  ignore_errors: yes

- name: Set IP Address and Gateway for terminal
  command: "ip a add {{ ip }} dev ens160"
  when: ip is defined
  become: yes
  ignore_errors: yes

- name: Set GW for terminal
  command: "ip route add 10.0.0.0/8 dev ens160"
  when: ip is defined
  become: yes
  ignore_errors: yes

- name: Restart network
  command: systemctl restart NetworkManager.service
  become: yes
